import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';

const prisma = new PrismaClient();

async function main() {
  console.log('Clearing existing data...');
  await prisma.inquiryLead.deleteMany();
  await prisma.message.deleteMany();
  await prisma.favorite.deleteMany();
  await prisma.savedSearch.deleteMany();
  await prisma.listingImage.deleteMany();
  await prisma.listing.deleteMany();
  await prisma.user.deleteMany();

  console.log('Creating users...');
  const passwordHash = await bcrypt.hash('password123', 10);

  // Admin user
  const adminUser = await prisma.user.create({
    data: {
      name: 'System Admin',
      email: 'admin@truegear.com',
      passwordHash,
      role: 'ADMIN',
      phone: '(555) 019-2831',
    },
  });

  // Dealer 1: Lone Star Motors
  const dealer1 = await prisma.user.create({
    data: {
      name: 'Lone Star Motors',
      email: 'sales@lonestarmotors.com',
      passwordHash,
      role: 'DEALER',
      phone: '(214) 555-0144',
      dealerName: 'Lone Star Premier Auto Group',
      dealerRating: 4.9,
      dealerCity: 'Dallas',
      dealerState: 'TX',
      avatar: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=300&auto=format&fit=crop&q=80',
    },
  });

  // Dealer 2: Pacific Coast Auto
  const dealer2 = await prisma.user.create({
    data: {
      name: 'Pacific Coast Auto',
      email: 'contact@pacificcoastauto.com',
      passwordHash,
      role: 'DEALER',
      phone: '(415) 555-0189',
      dealerName: 'Pacific Coast Certified Pre-Owned',
      dealerRating: 4.8,
      dealerCity: 'San Francisco',
      dealerState: 'CA',
      avatar: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=300&auto=format&fit=crop&q=80',
    },
  });

  // Dealer 3: Metro Car Center
  const dealer3 = await prisma.user.create({
    data: {
      name: 'Metro Car Center',
      email: 'inventory@metrocarcenter.com',
      passwordHash,
      role: 'DEALER',
      phone: '(312) 555-0177',
      dealerName: 'Metro Chicago Auto Exchange',
      dealerRating: 4.7,
      dealerCity: 'Chicago',
      dealerState: 'IL',
      avatar: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=300&auto=format&fit=crop&q=80',
    },
  });

  // Private Seller
  const privateSeller = await prisma.user.create({
    data: {
      name: 'David Miller',
      email: 'david.m@gmail.com',
      passwordHash,
      role: 'BUYER',
      phone: '(512) 555-0133',
    },
  });

  // Buyer user for demo/testing
  const demoBuyer = await prisma.user.create({
    data: {
      name: 'Alex Johnson',
      email: 'buyer@truegear.com',
      passwordHash,
      role: 'BUYER',
      phone: '(512) 555-9821',
    },
  });

  console.log('Seeding 32 realistic car listings...');

  const listingsData = [
    // 1. Toyota Camry 2022 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Toyota',
      model: 'Camry',
      year: 2022,
      trim: 'SE Nightshade Edition',
      bodyType: 'Sedan',
      mileage: 24500,
      price: 21900, // Market avg is ~25,500 -> Great Deal (>10% below)
      vin: '4T1B11HK5NU109281',
      description: 'Clean Carfax, 1-owner 2022 Toyota Camry SE Nightshade. Sleek blacked-out alloy wheels, Toyota Safety Sense 2.5+, Apple CarPlay/Android Auto, and superb 39 MPG highway economy.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7767,
      lng: -96.797,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Celestial Silver Metallic',
      interiorColor: 'Black SofTex',
      condition: 'Used',
      engine: '2.5L I4 DOHC 203hp',
      features: JSON.stringify(['Backup Camera', 'Apple CarPlay', 'Lane Departure Warning', 'Adaptive Cruise Control', 'Keyless Entry', 'Bluetooth']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 6,
      images: [
        'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 2. Toyota Camry 2021 - Fair Deal
    {
      sellerId: dealer2.id,
      make: 'Toyota',
      model: 'Camry',
      year: 2021,
      trim: 'XLE',
      bodyType: 'Sedan',
      mileage: 28000,
      price: 24800, // Market avg ~25,000 -> Fair Deal
      vin: '4T1B11HK9MU281920',
      description: 'Luxurious Camry XLE with full leather upholstery, panoramic moonroof, JBL premium audio, ventilated front seats, and blind-spot monitoring. Pristine condition with regular service records.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Wind Chill Pearl',
      interiorColor: 'Macadamia Leather',
      condition: 'Certified Pre-Owned',
      engine: '2.5L 4-Cylinder 206hp',
      features: JSON.stringify(['Leather Seats', 'Sunroof/Moonroof', 'Blind Spot Monitor', 'JBL Audio', 'Heated/Cooled Seats', 'Navigation']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 8,
      images: [
        'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 3. Toyota Camry 2022 - High Price
    {
      sellerId: dealer3.id,
      make: 'Toyota',
      model: 'Camry',
      year: 2022,
      trim: 'TRD V6',
      bodyType: 'Sedan',
      mileage: 26000,
      price: 32500, // >10% above standard avg ~26,000 -> High Price
      vin: '4T1KZ1HK4NU391024',
      description: 'Enthusiast-tuned Camry TRD with 301HP 3.5L V6, sport-tuned exhaust, matte-black 19" TRD alloys, red seat belts, and aggressive aero body kit. Rare find.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.8781,
      lng: -87.6298,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Cavalry Blue with Midnight Black Roof',
      interiorColor: 'Black TRD Fabric with Red Accents',
      condition: 'Used',
      engine: '3.5L V6 301hp',
      features: JSON.stringify(['TRD Sport Exhaust', 'Sport Suspension', 'JBL Sound', 'Alloy Wheels', 'Rear Spoiler', 'Apple CarPlay']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 4. Honda Civic 2023 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Honda',
      model: 'Civic',
      year: 2023,
      trim: 'Sport Touring Hatchback',
      bodyType: 'Hatchback',
      mileage: 14200,
      price: 24500, // Market avg ~28,000 -> Great Deal
      vin: '19XFC1F72PE102948',
      description: 'Fully loaded Civic Sport Touring Hatchback. Turbocharged engine, Bose 12-speaker audio system, wireless Apple CarPlay/Android Auto, leather seats, and 6-speed manual option versatility.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7831,
      lng: -96.8067,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Sonic Gray Pearl',
      interiorColor: 'Black Leather',
      condition: 'Used',
      engine: '1.5L Turbo 180hp',
      features: JSON.stringify(['Bose Sound', 'Wireless Charging', 'Moonroof', 'Adaptive Cruise', 'Lane Keep Assist', 'Heated Seats']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 5. Honda Civic 2022 - Fair Deal
    {
      sellerId: dealer2.id,
      make: 'Honda',
      model: 'Civic',
      year: 2022,
      trim: 'EX Sedan',
      bodyType: 'Sedan',
      mileage: 19500,
      price: 23900, // Market avg ~24,500 -> Fair Deal
      vin: '19XFC1F54NE837201',
      description: 'Reliable and fuel-efficient Civic EX Sedan with power moonroof, heated seats, blind-spot info system, and turbo power. Over 40 MPG highway.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94103',
      lat: 37.7712,
      lng: -122.4201,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Platinum White Pearl',
      interiorColor: 'Black Cloth',
      condition: 'Used',
      engine: '1.5L Turbo 180hp',
      features: JSON.stringify(['Sunroof', 'Heated Seats', 'Backup Camera', 'Apple CarPlay', 'Remote Start']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 6. Honda Civic 2023 - High Price
    {
      sellerId: privateSeller.id,
      make: 'Honda',
      model: 'Civic',
      year: 2023,
      trim: 'Si',
      bodyType: 'Sedan',
      mileage: 12000,
      price: 31000, // High Price
      vin: '19XFC1F99PE901824',
      description: 'Civic Si 6-speed manual with helical limited-slip differential, sport seats with red stitching, customized ceramic tint, and rev-matching downshifts.',
      city: 'Austin',
      state: 'TX',
      zip: '78701',
      lat: 30.2672,
      lng: -97.7431,
      fuelType: 'Gasoline',
      transmission: 'Manual',
      drivetrain: 'FWD',
      exteriorColor: 'Blazing Orange Pearl',
      interiorColor: 'Black & Red Sport Cloth',
      condition: 'Used',
      engine: '1.5L Turbo 200hp',
      features: JSON.stringify(['Manual 6-Speed', 'Limited Slip Diff', 'Bose Audio', 'Apple CarPlay', 'Sport Mode']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 7. Ford F-150 2022 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Ford',
      model: 'F-150',
      year: 2022,
      trim: 'Lariat SuperCrew 4x4',
      bodyType: 'Truck',
      mileage: 31000,
      price: 43500, // Market avg ~49,500 -> Great Deal
      vin: '1FTFW1ED5NFA98124',
      description: 'Stunning Oxford White F-150 Lariat 4WD. Powered by the potent 3.5L EcoBoost twin-turbo V6, 12" SYNC 4 touchscreen, B&O Sound, heated/cooled leather seats, and FX4 Off-Road package.',
      city: 'Dallas',
      state: 'TX',
      zip: '75207',
      lat: 32.7904,
      lng: -96.8152,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Oxford White',
      interiorColor: 'Black Leather',
      condition: 'Certified Pre-Owned',
      engine: '3.5L V6 EcoBoost 400hp',
      features: JSON.stringify(['Tow Package', 'Navigation', '4WD', 'Heated/Cooled Seats', 'B&O Audio', 'Panoramic Sunroof', '360 Camera']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 7,
      images: [
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 8. Ford F-150 2021 - Fair Deal
    {
      sellerId: dealer3.id,
      make: 'Ford',
      model: 'F-150',
      year: 2021,
      trim: 'XLT SuperCrew 4x4',
      bodyType: 'Truck',
      mileage: 38000,
      price: 38900, // Fair deal
      vin: '1FTFW1E87MFA10294',
      description: 'Solid workhorse F-150 XLT with max trailer tow package, chrome appearance package, extended range fuel tank, and 2.7L EcoBoost engine with tremendous torque and towing capacity.',
      city: 'Chicago',
      state: 'IL',
      zip: '60607',
      lat: 41.8745,
      lng: -87.6521,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Carbonized Gray Metallic',
      interiorColor: 'Medium Dark Slate',
      condition: 'Used',
      engine: '2.7L V6 EcoBoost 325hp',
      features: JSON.stringify(['4WD', 'Trailer Hitch', 'Blind Spot Monitor', 'Apple CarPlay', 'Remote Start']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 9,
      images: [
        'https://images.unsplash.com/photo-1605893477799-b99e3b8b93fe?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 9. Ford F-150 2022 - High Price
    {
      sellerId: dealer1.id,
      make: 'Ford',
      model: 'F-150',
      year: 2022,
      trim: 'King Ranch 4x4',
      bodyType: 'Truck',
      mileage: 22000,
      price: 58900, // High Price
      vin: '1FTFW1ED3NFA48291',
      description: 'Ultra-luxurious King Ranch F-150 with authentic Del Rio leather, massaging multicontour seats, power deployable running boards, and 7.2kW Pro Power Onboard generator.',
      city: 'Fort Worth',
      state: 'TX',
      zip: '76102',
      lat: 32.7555,
      lng: -97.3308,
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Smoked Quartz Tinted Clearcoat',
      interiorColor: 'Java Leather',
      condition: 'Used',
      engine: '3.5L PowerBoost Full Hybrid V6 430hp',
      features: JSON.stringify(['Pro Power Onboard', 'Massage Seats', 'B&O Unleashed 18-Speaker', 'Adaptive Cruise', 'Panoramic Roof']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 6,
      images: [
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 10. Tesla Model 3 2022 - Great Deal
    {
      sellerId: dealer2.id,
      make: 'Tesla',
      model: 'Model 3',
      year: 2022,
      trim: 'Long Range AWD',
      bodyType: 'Sedan',
      mileage: 21500,
      price: 27900, // Market avg ~32,500 -> Great Deal
      vin: '5YJ3E1EB7NF291048',
      description: 'Dual Motor All-Wheel Drive Tesla Model 3 Long Range with 358 miles EPA range, AMD Ryzen processor, heated steering wheel, heat pump, and premium audio system.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94105',
      lat: 37.7891,
      lng: -122.3982,
      fuelType: 'Electric',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Midnight Silver Metallic',
      interiorColor: 'All Black Premium',
      condition: 'Used',
      engine: 'Dual AC Electric Motors 346hp',
      features: JSON.stringify(['Autopilot', 'Navigation', 'Heated Seats front & rear', 'Glass Roof', 'Wireless Charging', 'Dashcam/Sentry Mode']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 11. Tesla Model 3 2023 - Fair Deal
    {
      sellerId: dealer2.id,
      make: 'Tesla',
      model: 'Model 3',
      year: 2023,
      trim: 'Standard Range RWD',
      bodyType: 'Sedan',
      mileage: 15400,
      price: 29800, // Fair Deal
      vin: '5YJ3E1EA5PF391029',
      description: 'LFP battery chemistry allows daily charging to 100%. Excellent commuter with instant electric torque, Autopilot highway assist, and minimalist cockpit.',
      city: 'San Jose',
      state: 'CA',
      zip: '95110',
      lat: 37.3382,
      lng: -121.8863,
      fuelType: 'Electric',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Pearl White Multi-Coat',
      interiorColor: 'White Premium Interior',
      condition: 'Used',
      engine: 'Rear Electric Motor 271hp',
      features: JSON.stringify(['Autopilot', 'Glass Roof', 'Power Liftgate', 'White Interior', 'Navigation']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 2,
      images: [
        'https://images.unsplash.com/photo-1536700503339-1e4b06520771?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 12. Tesla Model 3 2022 - High Price
    {
      sellerId: privateSeller.id,
      make: 'Tesla',
      model: 'Model 3',
      year: 2022,
      trim: 'Performance AWD',
      bodyType: 'Sedan',
      mileage: 18000,
      price: 39500, // High Price
      vin: '5YJ3E1EC9NF482910',
      description: 'Model 3 Performance with Full Self-Driving (FSD) package fully paid ($12k value), 0-60 in 3.1 seconds, 20" Überturbine Wheels, Track Mode, and carbon fiber spoiler.',
      city: 'Austin',
      state: 'TX',
      zip: '78704',
      lat: 30.2452,
      lng: -97.7612,
      fuelType: 'Electric',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Deep Blue Metallic',
      interiorColor: 'Black & White',
      condition: 'Used',
      engine: 'Dual Motor Performance 450hp',
      features: JSON.stringify(['Full Self Driving Hardware', 'Track Mode', '20" Wheels', 'Performance Brakes', 'Glass Roof']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 13. BMW 3 Series 2021 - Great Deal
    {
      sellerId: dealer3.id,
      make: 'BMW',
      model: '3 Series',
      year: 2021,
      trim: '330i xDrive',
      bodyType: 'Sedan',
      mileage: 29500,
      price: 28900, // Market avg ~33,000 -> Great Deal
      vin: 'WBA5R7C58MFL19203',
      description: 'BMW Certified Pre-Owned 330i xDrive. M Sport Package, 19" Bicolor wheels, Live Cockpit Pro with iDrive 7, heated front seats & steering wheel, and ambient interior lighting.',
      city: 'Chicago',
      state: 'IL',
      zip: '60611',
      lat: 41.8955,
      lng: -87.6244,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Portimao Blue Metallic',
      interiorColor: 'Cognac Vernasca Leather',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo I4 255hp',
      features: JSON.stringify(['M Sport Package', 'Navigation', 'AWD', 'Heated Seats', 'Harman Kardon Audio', 'Sunroof']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 7,
      images: [
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 14. BMW 3 Series 2022 - Fair Deal
    {
      sellerId: dealer2.id,
      make: 'BMW',
      model: '3 Series',
      year: 2022,
      trim: '330i RWD',
      bodyType: 'Sedan',
      mileage: 26000,
      price: 33500, // Fair deal
      vin: 'WBA5R7C52NFL28391',
      description: 'Single-owner executive lease return in pristine condition. Convenience package, park distance control, Apple CarPlay, wireless device charging, and LED headlights with cornering lights.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94110',
      lat: 37.7511,
      lng: -122.4182,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Mineral White Metallic',
      interiorColor: 'Canberra Beige SensaTec',
      condition: 'Used',
      engine: '2.0L Turbo I4 255hp',
      features: JSON.stringify(['Comfort Access', 'Sunroof', 'Active Blind Spot', 'Apple CarPlay', 'Parking Sensors']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 15. Toyota RAV4 2022 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Toyota',
      model: 'RAV4',
      year: 2022,
      trim: 'XLE Premium AWD',
      bodyType: 'SUV',
      mileage: 23000,
      price: 27400, // Market avg ~31,000 -> Great Deal
      vin: '2T3P1RFV7NW102948',
      description: 'America\'s favorite compact SUV. Loaded XLE Premium with SofTex synthetic leather, power moonroof, height-adjustable power liftgate, 19" alloy wheels, and Toyota Safety Sense 2.0.',
      city: 'Dallas',
      state: 'TX',
      zip: '75220',
      lat: 32.8654,
      lng: -96.8621,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Magnetic Gray Metallic',
      interiorColor: 'Black SofTex',
      condition: 'Used',
      engine: '2.5L 4-Cylinder 203hp',
      features: JSON.stringify(['AWD', 'Power Liftgate', 'Sunroof', 'Blind Spot Monitor', 'Apple CarPlay', 'Roof Rails']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 6,
      images: [
        'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 16. Toyota RAV4 2022 - Fair Deal
    {
      sellerId: dealer2.id,
      make: 'Toyota',
      model: 'RAV4',
      year: 2022,
      trim: 'Hybrid Limited',
      bodyType: 'SUV',
      mileage: 24500,
      price: 33800, // Fair deal
      vin: '2T3P1RFV5NW829104',
      description: 'High-spec RAV4 Hybrid Limited delivering 40 MPG combined. Features heated & ventilated front seats, digital rearview mirror, bird’s eye view camera, and premium JBL 11-speaker system.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94115',
      lat: 37.7885,
      lng: -122.4345,
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Ruby Flare Pearl',
      interiorColor: 'Nutmeg Leather',
      condition: 'Certified Pre-Owned',
      engine: '2.5L Hybrid 219hp',
      features: JSON.stringify(['Hybrid 40 MPG', '360 Camera', 'JBL Sound', 'Ventilated Seats', 'Heated Steering Wheel', 'Navigation']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 8,
      images: [
        'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 17. Toyota RAV4 2023 - High Price
    {
      sellerId: dealer3.id,
      make: 'Toyota',
      model: 'RAV4',
      year: 2023,
      trim: 'TRD Off-Road',
      bodyType: 'SUV',
      mileage: 16000,
      price: 39500, // High Price
      vin: '2T3P1RFV9PW482910',
      description: 'Rugged TRD Off-Road package with red coil springs, twin-tube shocks, matte-black 18" flow-formed alloy wheels, Falken Wildpeak A/T trail tires, and Multi-Terrain Select.',
      city: 'Chicago',
      state: 'IL',
      zip: '60614',
      lat: 41.9214,
      lng: -87.6536,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Army Green with Ice Edge Roof',
      interiorColor: 'Black SofTex with Red Stitching',
      condition: 'Used',
      engine: '2.5L 4-Cylinder 203hp',
      features: JSON.stringify(['Off-Road Package', 'All-Terrain Tires', 'Roof Rack', 'TRD Suspension', 'Multi-Terrain Select']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 18. Porsche 911 2021 - Great Deal
    {
      sellerId: dealer2.id,
      make: 'Porsche',
      model: '911',
      year: 2021,
      trim: 'Carrera S (992)',
      bodyType: 'Coupe',
      mileage: 18500,
      price: 114000, // Market avg ~128,000 -> Great Deal
      vin: 'WP0AB2A97MS281920',
      description: 'Spectacular 992 Carrera S. Twin-turbo 3.0L flat-six making 443 hp, 8-speed PDK transmission, Sport Chrono Package, Sport Exhaust System with black tailpipes, PASM Sport Suspension, and 20/21" RS Spyder Design Wheels.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94123',
      lat: 37.8005,
      lng: -122.4371,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Chalk',
      interiorColor: 'Black Leather with Chalk Stitching',
      condition: 'Certified Pre-Owned',
      engine: '3.0L Twin-Turbo Flat-6 443hp',
      features: JSON.stringify(['Sport Chrono', 'Sport Exhaust', 'PASM Suspension', 'Bose Surround', '14-Way Sport Seats', 'Glass Sunroof']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 6,
      images: [
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 19. Porsche 911 2022 - Fair Deal
    {
      sellerId: dealer1.id,
      make: 'Porsche',
      model: '911',
      year: 2022,
      trim: 'Carrera 4S',
      bodyType: 'Coupe',
      mileage: 14000,
      price: 132000, // Fair deal
      vin: 'WP0AB2A92NS491028',
      description: 'All-weather supercar performance. Carrera 4S with all-wheel drive, Rear-Axle Steering, Front Axle Lift system, Burmester High-End Surround Sound, and carbon fiber interior trim.',
      city: 'Dallas',
      state: 'TX',
      zip: '75225',
      lat: 32.8687,
      lng: -96.7925,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Gentian Blue Metallic',
      interiorColor: 'Slate Grey Leather',
      condition: 'Used',
      engine: '3.0L Twin-Turbo Flat-6 443hp',
      features: JSON.stringify(['AWD', 'Front Axle Lift', 'Rear Axle Steering', 'Burmester Audio', 'LED Matrix Headlights']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 20. Jeep Wrangler 2021 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Jeep',
      model: 'Wrangler',
      year: 2021,
      trim: 'Unlimited Rubicon 4x4',
      bodyType: 'SUV',
      mileage: 28400,
      price: 36900, // Market avg ~42,000 -> Great Deal
      vin: '1C4HJXFN9MW281903',
      description: 'Legendary trail machine. Wrangler Rubicon with Rock-Trac 4:1 heavy-duty part-time 4WD, electronic front sway bar disconnect, Tru-Lok front & rear locking differentials, 33" all-terrain tires, and removable hardtop.',
      city: 'Dallas',
      state: 'TX',
      zip: '75234',
      lat: 32.9238,
      lng: -96.8856,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Firecracker Red',
      interiorColor: 'Black Cloth with Rubicon Red Stitching',
      condition: 'Used',
      engine: '3.6L V6 eTorque 285hp',
      features: JSON.stringify(['4x4 Rubicon', 'Locking Differentials', 'Sway Bar Disconnect', 'Removable Doors/Roof', 'Alpine Premium Sound']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 7,
      images: [
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 21. Jeep Wrangler 2022 - Fair Deal
    {
      sellerId: dealer3.id,
      make: 'Jeep',
      model: 'Wrangler',
      year: 2022,
      trim: 'Unlimited Sahara 4xe',
      bodyType: 'SUV',
      mileage: 22000,
      price: 41500, // Fair deal
      vin: '1C4JJXP63NW829103',
      description: 'Plug-in Hybrid Wrangler 4xe. Provides 21 miles of pure electric range for silent trail exploration, 375 combined horsepower, leather trimmed seats, and body-color hardtop.',
      city: 'Chicago',
      state: 'IL',
      zip: '60622',
      lat: 41.9032,
      lng: -87.6789,
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Hydro Blue Pearlcoat',
      interiorColor: 'Dark Saddle Leather',
      condition: 'Used',
      engine: '2.0L Turbo PHEV 375hp',
      features: JSON.stringify(['PHEV Plug-in', 'Leather Seats', 'Navigation 8.4"', 'Cold Weather Group', 'Alpine Sound']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 22. Chevrolet Corvette 2022 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Chevrolet',
      model: 'Corvette',
      year: 2022,
      trim: 'Stingray 2LT with Z51',
      bodyType: 'Coupe',
      mileage: 11200,
      price: 66800, // Market avg ~75,000 -> Great Deal
      vin: '1G1YB2D47N5102948',
      description: 'Mid-engine masterpiece. C8 Corvette with Z51 Performance Package (performance brakes, suspension, exhaust, rear spoiler, eLSD), GT2 bucket seats in Napa leather, front lift with memory, and Bose 14-speaker sound.',
      city: 'Dallas',
      state: 'TX',
      zip: '75204',
      lat: 32.8012,
      lng: -96.7891,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Torch Red',
      interiorColor: 'Jet Black Leather',
      condition: 'Used',
      engine: '6.2L LT2 V8 495hp',
      features: JSON.stringify(['Z51 Performance Pack', 'Front Lift Memory', 'Performance Data Recorder', 'Bose 14-Speaker', 'Heads-Up Display']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 23. Chevrolet Silverado 1500 2022 - Fair Deal
    {
      sellerId: dealer1.id,
      make: 'Chevrolet',
      model: 'Silverado 1500',
      year: 2022,
      trim: 'LTZ Crew Cab 4WD',
      bodyType: 'Truck',
      mileage: 33000,
      price: 44900, // Fair deal
      vin: '1GCPYEEF4NZ102948',
      description: 'Refreshed interior Silverado LTZ featuring a massive 13.4" touchscreen, 12.3" digital gauge cluster, 5.3L EcoTec3 V8, power up/down tailgate, and advanced trailering cameras.',
      city: 'Dallas',
      state: 'TX',
      zip: '75215',
      lat: 32.7482,
      lng: -96.7621,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Glacier Blue Metallic',
      interiorColor: 'Gideon / Very Dark Atmosphere Leather',
      condition: 'Used',
      engine: '5.3L V8 EcoTec3 355hp',
      features: JSON.stringify(['13.4" Screen', 'Chevy Safety Assist', 'Bose Audio', 'Heated/Ventilated Seats', 'Multifunction Tailgate']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 7,
      images: [
        'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 24. Mercedes-Benz C-Class 2022 - Great Deal
    {
      sellerId: dealer3.id,
      make: 'Mercedes-Benz',
      model: 'C-Class',
      year: 2022,
      trim: 'C 300 4MATIC',
      bodyType: 'Sedan',
      mileage: 22000,
      price: 33900, // Market avg ~39,000 -> Great Deal
      vin: 'W1KZF8EB8NR192038',
      description: 'Next-generation W206 C-Class with S-Class inspired technology. 11.9" portrait touchscreen with wireless MBUX, 64-color ambient lighting, Burmester 3D sound, panoramic roof, and mild-hybrid turbo engine.',
      city: 'Chicago',
      state: 'IL',
      zip: '60654',
      lat: 41.8921,
      lng: -87.6341,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Obsidian Black Metallic',
      interiorColor: 'Sienna Brown MB-Tex',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo I4 with EQ Boost 255hp',
      features: JSON.stringify(['MBUX Navigation', 'Burmester 3D Sound', 'Ambient Lighting', 'Panoramic Roof', 'Blind Spot Assist']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 25. Hyundai Tucson 2023 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Hyundai',
      model: 'Tucson',
      year: 2023,
      trim: 'Hybrid Limited AWD',
      bodyType: 'SUV',
      mileage: 18500,
      price: 29900, // Market avg ~34,500 -> Great Deal
      vin: 'KM8J3DA44PU102948',
      description: 'Top-of-the-line Tucson Hybrid Limited. Remote Smart Parking Assist, blind-spot view monitor, panoramic sunroof, Bose audio, heated & ventilated leather seats, and 37 MPG combined.',
      city: 'Dallas',
      state: 'TX',
      zip: '75240',
      lat: 32.9324,
      lng: -96.7981,
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Amazon Gray',
      interiorColor: 'Gray Leather',
      condition: 'Used',
      engine: '1.6L Turbo Hybrid 226hp',
      features: JSON.stringify(['Remote Smart Parking', 'Panoramic Sunroof', 'Blind Spot Cameras', 'Bose Premium Audio', 'AWD']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1581540222194-0def2dda95b8?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 26. Subaru Outback 2022 - Fair Deal
    {
      sellerId: dealer2.id,
      make: 'Subaru',
      model: 'Outback',
      year: 2022,
      trim: 'Wilderness AWD',
      bodyType: 'Wagon',
      mileage: 26000,
      price: 31900, // Fair deal
      vin: '4S4BTANC7N3102948',
      description: 'Outback Wilderness with 9.5" ground clearance, Yokohama GEOLANDAR all-terrain tires, enhanced dual-function X-MODE, reinforced roof rails capable of holding a rooftop tent, and StarTex water-repellent upholstery.',
      city: 'Seattle',
      state: 'WA',
      zip: '98101',
      lat: 47.6062,
      lng: -122.3321,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Geyser Blue',
      interiorColor: 'Gray StarTex',
      condition: 'Used',
      engine: '2.4L Turbo Boxer 260hp',
      features: JSON.stringify(['Symmetrical AWD', '9.5" Clearance', 'EyeSight Safety', 'All-Terrain Tires', 'Roof Rack']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 6,
      images: [
        'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 27. Audi Q5 2022 - Fair Deal
    {
      sellerId: dealer3.id,
      make: 'Audi',
      model: 'Q5',
      year: 2022,
      trim: '45 TFSI Premium Plus quattro',
      bodyType: 'SUV',
      mileage: 24000,
      price: 36500, // Fair deal
      vin: 'WA1BNAFY4N2102948',
      description: 'Sophisticated Audi Q5 with legendary quattro all-wheel drive, Audi virtual cockpit plus 12.3", Bang & Olufsen 3D sound system, panoramic sunroof, top view camera system, and adaptive cruise assist.',
      city: 'Chicago',
      state: 'IL',
      zip: '60610',
      lat: 41.9001,
      lng: -87.6378,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Mythos Black Metallic',
      interiorColor: 'Okapi Brown Leather',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo 4-Cylinder 261hp',
      features: JSON.stringify(['quattro AWD', 'Virtual Cockpit', 'Bang & Olufsen Sound', 'Panoramic Sunroof', '360 Camera']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 28. Mazda CX-5 2023 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Mazda',
      model: 'CX-5',
      year: 2023,
      trim: '2.5 Turbo Signature AWD',
      bodyType: 'SUV',
      mileage: 14500,
      price: 30800, // Market avg ~35,000 -> Great Deal
      vin: 'JM3KFBCM9P0192038',
      description: 'Near-luxury compact crossover with genuine layered wood trim, Caturra Brown Nappa leather, 256 hp turbo engine, i-Activ AWD, 360-degree monitor, and Bose 10-speaker audio.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7845,
      lng: -96.8012,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Soul Red Crystal Metallic',
      interiorColor: 'Caturra Brown Nappa Leather',
      condition: 'Used',
      engine: '2.5L Turbo 256hp',
      features: JSON.stringify(['Nappa Leather', 'Turbo 256hp', 'Bose Audio', 'Heads Up Display', 'Ventilated Seats']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 29. Ford Mustang 2021 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Ford',
      model: 'Mustang',
      year: 2021,
      trim: 'GT Premium Fastback',
      bodyType: 'Coupe',
      mileage: 21000,
      price: 33900, // Market avg ~39,000 -> Great Deal
      vin: '1FA6P8CF8M5192038',
      description: 'Classic American muscle. 5.0L Coyote V8 pumping out 460 HP, active valve performance exhaust with quad tips, 12" digital instrument cluster, B&O 12-speaker sound, and heated/cooled leather seats.',
      city: 'Dallas',
      state: 'TX',
      zip: '75206',
      lat: 32.8245,
      lng: -96.7698,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Shadow Black',
      interiorColor: 'Showstopper Red Leather',
      condition: 'Used',
      engine: '5.0L Coyote V8 460hp',
      features: JSON.stringify(['Active Exhaust', 'Digital Cluster', 'B&O Sound', 'Track Apps', 'Heated/Cooled Seats']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 30. Ford Mustang 2022 - High Price
    {
      sellerId: privateSeller.id,
      make: 'Ford',
      model: 'Mustang',
      year: 2022,
      trim: 'Mach 1 Handling Package',
      bodyType: 'Coupe',
      mileage: 9500,
      price: 52000, // High Price
      vin: '1FA6P8R04N5281920',
      description: 'Track-ready Mach 1 with Tremec 6-speed manual rev-matching transmission, MagneRide damping system, Handling Package with wider Michelin Pilot Sport Cup 2 tires, and Shelby GT500 cooling components.',
      city: 'Austin',
      state: 'TX',
      zip: '78703',
      lat: 30.2912,
      lng: -97.7654,
      fuelType: 'Gasoline',
      transmission: 'Manual',
      drivetrain: 'RWD',
      exteriorColor: 'Fighter Jet Gray',
      interiorColor: 'Ebony with Orange Accents',
      condition: 'Used',
      engine: '5.0L V8 470hp',
      features: JSON.stringify(['Tremec 6-Speed Manual', 'MagneRide Suspension', 'Handling Package', 'Mach 1 Appearance', 'Track Pack']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 2,
      images: [
        'https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 31. Kia Telluride 2022 - Fair Deal
    {
      sellerId: dealer3.id,
      make: 'Kia',
      model: 'Telluride',
      year: 2022,
      trim: 'SX Prestige AWD',
      bodyType: 'SUV',
      mileage: 29000,
      price: 37900, // Fair deal
      vin: '5XYP54HC7NG102948',
      description: 'Award-winning 3-row family SUV in top SX Prestige trim. Dual sunroofs, Harman Kardon 10-speaker audio, Nappa leather with heated/ventilated 1st and 2nd row captain chairs, head-up display, and Highway Driving Assist 2.',
      city: 'Chicago',
      state: 'IL',
      zip: '60618',
      lat: 41.9421,
      lng: -87.7012,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Dark Moss',
      interiorColor: 'Dune Brown Nappa Leather',
      condition: 'Used',
      engine: '3.8L V6 291hp',
      features: JSON.stringify(['3-Row Seating', 'Captain Chairs', 'Dual Sunroofs', 'Harman Kardon Audio', 'Heads Up Display', 'AWD']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 6,
      images: [
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 32. BMW M4 2022 - Fair Deal
    {
      sellerId: dealer2.id,
      make: 'BMW',
      model: 'M4',
      year: 2022,
      trim: 'Competition xDrive Coupe',
      bodyType: 'Coupe',
      mileage: 16500,
      price: 74900, // Fair deal
      vin: 'WBS43AZ00NFP10294',
      description: '503 HP S58 twin-turbo inline-6 with M xDrive all-wheel drive, M Carbon Bucket Seats, carbon fiber roof and interior trim, laser headlights, and M Drivers Package.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94109',
      lat: 37.7925,
      lng: -122.4215,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Isle of Man Green Metallic',
      interiorColor: 'Kyalami Orange / Black Full Merino Leather',
      condition: 'Certified Pre-Owned',
      engine: '3.0L Twin-Turbo I6 503hp',
      features: JSON.stringify(['M xDrive AWD', 'Carbon Bucket Seats', 'Carbon Roof', 'Laserlights', 'Harman Kardon Audio']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200&auto=format&fit=crop&q=80',
      ],
    },
  
    // 33. Lexus RX 350 2022 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Lexus',
      model: 'RX 350',
      year: 2022,
      trim: 'F SPORT AWD',
      bodyType: 'SUV',
      mileage: 22000,
      price: 41500,
      vin: '2T2BZMCA4NC109283',
      description: 'Stunning Lexus RX 350 F SPORT with Mark Levinson 15-speaker audio, triple-beam LED headlights, panorama glass roof, heated/ventilated seats, and comprehensive LSS+ 2.0 safety suite.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7767,
      lng: -96.797,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Ultra White',
      interiorColor: 'Circuit Red Leather',
      condition: 'Certified Pre-Owned',
      engine: '3.5L V6 295hp',
      features: JSON.stringify(['Mark Levinson Audio', 'F SPORT Tuned Suspension', 'Panoramic Roof', 'Heated & Ventilated Seats', 'Navigation']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 6,
      images: [
        'https://images.unsplash.com/photo-1508974239320-0a029497e820?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 34. Lexus ES 300h 2023 - Fair Deal
    {
      sellerId: dealer2.id,
      make: 'Lexus',
      model: 'ES 300h',
      year: 2023,
      trim: 'Ultra Luxury Hybrid',
      bodyType: 'Sedan',
      mileage: 16800,
      price: 43900,
      vin: '58ABZ1B17PU089211',
      description: 'Ultra Luxury ES 300h achieving 44 MPG combined. Semi-aniline leather, genuine wood trim, heads-up display, hands-free power trunk, and whisper-quiet hybrid serenity.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Eminent White Pearl',
      interiorColor: 'Acorn Semi-Aniline Leather',
      condition: 'Used',
      engine: '2.5L 4-Cylinder Hybrid 215hp',
      features: JSON.stringify(['Semi-Aniline Leather', '44 MPG Hybrid', 'Heads Up Display', 'Panoramic Glass Roof', 'Blind Spot Monitor']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 35. Nissan Rogue 2022 - Great Deal
    {
      sellerId: dealer3.id,
      make: 'Nissan',
      model: 'Rogue',
      year: 2022,
      trim: 'SV AWD',
      bodyType: 'SUV',
      mileage: 25400,
      price: 21900,
      vin: 'JN8BT3BB6NW284910',
      description: 'Practical and modern Rogue SV with 1.5L VC-Turbo engine, Intelligent All-Wheel Drive, ProPILOT Assist, dual-zone automatic climate control, and remote engine start.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.8781,
      lng: -87.6298,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Gun Metallic',
      interiorColor: 'Charcoal Cloth',
      condition: 'Used',
      engine: '1.5L VC-Turbo 201hp',
      features: JSON.stringify(['ProPILOT Assist', 'Intelligent AWD', 'Apple CarPlay', 'Remote Start', 'Blind Spot Warning']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1592853625597-7d17be820d0c?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 36. Nissan GT-R 2021 - High Price
    {
      sellerId: dealer1.id,
      make: 'Nissan',
      model: 'GT-R',
      year: 2021,
      trim: 'Premium AWD',
      bodyType: 'Coupe',
      mileage: 12000,
      price: 119500,
      vin: 'JN1AR5EF7MM710294',
      description: 'The legendary Godzilla. Handcrafted 3.8-liter twin-turbo V6 with 565 HP, ATTESA E-TS All-Wheel Drive, Bilstein DampTronic suspension, Brembo braking system, and Bose sound.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7845,
      lng: -96.8012,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Super Silver QuadCoat',
      interiorColor: 'Amber Hand-Stitched Leather',
      condition: 'Used',
      engine: '3.8L Twin-Turbo V6 565hp',
      features: JSON.stringify(['ATTESA AWD', 'Brembo Brakes', 'Bilstein DampTronic', 'Titanium Exhaust', 'Recaro Seats']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 37. Volkswagen Golf GTI 2023 - Great Deal (Hatchback & Manual!)
    {
      sellerId: dealer2.id,
      make: 'Volkswagen',
      model: 'Golf GTI',
      year: 2023,
      trim: 'SE 6-Speed Manual',
      bodyType: 'Hatchback',
      mileage: 14000,
      price: 28900,
      vin: '3VW547AU8PM092831',
      description: 'Purist delight Mark 8 Golf GTI equipped with a silky 6-speed manual transmission, VAQ limited-slip differential lock, Harman Kardon audio, sunroof, and plaid sport seats.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94103',
      lat: 37.779,
      lng: -122.415,
      fuelType: 'Gasoline',
      transmission: 'Manual',
      drivetrain: 'FWD',
      exteriorColor: 'Kings Red Metallic',
      interiorColor: 'Titan Black Scalepaper Plaid',
      condition: 'Used',
      engine: '2.0L Turbo 241hp',
      features: JSON.stringify(['6-Speed Manual', 'Limited Slip Diff', 'Harman Kardon Audio', 'Plaid Sport Seats', 'Digital Cockpit Pro']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 38. Volkswagen Tiguan 2022 - Fair Deal
    {
      sellerId: dealer3.id,
      make: 'Volkswagen',
      model: 'Tiguan',
      year: 2022,
      trim: 'SEL R-Line 4MOTION',
      bodyType: 'SUV',
      mileage: 24000,
      price: 27500,
      vin: '3VV4B7AX7NM192044',
      description: 'Sporty Tiguan SEL R-Line with 4MOTION All-Wheel Drive, panoramic sunroof, 20-inch alloy wheels, Fender premium audio, ventilated leather seats, and IQ.DRIVE safety suite.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.882,
      lng: -87.625,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Deep Black Pearl',
      interiorColor: 'Storm Gray Leather',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo 184hp',
      features: JSON.stringify(['4MOTION AWD', 'Panoramic Sunroof', 'Fender Audio', 'Ventilated Seats', 'R-Line Exterior']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 39. Volvo V60 Cross Country 2022 - Great Deal (Wagon!)
    {
      sellerId: dealer2.id,
      make: 'Volvo',
      model: 'V60',
      year: 2022,
      trim: 'Cross Country B5 AWD',
      bodyType: 'Wagon',
      mileage: 21500,
      price: 36800,
      vin: 'YV4102SK7N1294810',
      description: 'The definitive luxury all-road wagon. 8.3-inch ground clearance, standard All-Wheel Drive, Google built-in infotainment, Bowers & Wilkins sound option, and ultra-comfortable orthopedic seats.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Pine Grey Metallic',
      interiorColor: 'Amber Nappa Leather',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo Mild Hybrid 247hp',
      features: JSON.stringify(['Cross Country Raised Suspension', 'AWD', 'Pilot Assist', 'Panoramic Sunroof', 'Bowers & Wilkins Audio']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 40. Volvo XC90 Recharge 2023 - Fair Deal (PHEV!)
    {
      sellerId: dealer1.id,
      make: 'Volvo',
      model: 'XC90',
      year: 2023,
      trim: 'Recharge Plus AWD 7-Passenger',
      bodyType: 'SUV',
      mileage: 18500,
      price: 54900,
      vin: 'YV4BR0UL4P1394012',
      description: '7-passenger Plug-in Hybrid luxury SUV delivering 455 horsepower and 35 miles of pure electric driving. Air suspension, 360 camera, adaptive cruise with lane centering, and panoramic roof.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7767,
      lng: -96.797,
      fuelType: 'Plug-in Hybrid',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Crystal White',
      interiorColor: 'Charcoal Leather',
      condition: 'Used',
      engine: '2.0L Turbo PHEV 455hp',
      features: JSON.stringify(['Plug-in Hybrid 455hp', '3-Row 7-Seater', 'Air Suspension', '360 Surround Camera', 'Pilot Assist']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 41. Mazda MX-5 Miata 2022 - Great Deal (Convertible & Manual!)
    {
      sellerId: dealer1.id,
      make: 'Mazda',
      model: 'MX-5 Miata',
      year: 2022,
      trim: 'Club 6-Speed Manual',
      bodyType: 'Convertible',
      mileage: 11200,
      price: 26800,
      vin: 'JM1NDAM76N0491028',
      description: 'The world benchmark sports roadster. Bilstein sport dampers, limited-slip differential, Brembo/BBS package, crisp 6-speed manual, soft top drop in seconds, and pure 50:50 driving balance.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7845,
      lng: -96.8012,
      fuelType: 'Gasoline',
      transmission: 'Manual',
      drivetrain: 'RWD',
      exteriorColor: 'Jet Black Mica',
      interiorColor: 'Black Cloth with Red Stitching',
      condition: 'Used',
      engine: '2.0L SKYACTIV-G 181hp',
      features: JSON.stringify(['Manual 6-Speed', 'Brembo Brakes', 'BBS Wheels', 'Bilstein Dampers', 'LSD Differential']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 42. Porsche 911 Carrera S Cabriolet 2021 - High Price (Convertible!)
    {
      sellerId: dealer2.id,
      make: 'Porsche',
      model: '911',
      year: 2021,
      trim: 'Carrera S Cabriolet',
      bodyType: 'Convertible',
      mileage: 15400,
      price: 134000,
      vin: 'WP0CB2A96MS291048',
      description: 'Exquisite 992-generation 911 Carrera S Cabriolet in Guards Red. 443 hp twin-turbo flat-six, 8-speed PDK, Sport Chrono package, sport exhaust system, 18-way adaptive sport seats, and front axle lift.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Guards Red',
      interiorColor: 'Black Full Leather',
      condition: 'Used',
      engine: '3.0L Twin-Turbo Flat-6 443hp',
      features: JSON.stringify(['Sport Chrono Package', 'Sport Exhaust', 'Front Axle Lift', 'BOSE Surround Audio', '18-Way Sport Seats']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 43. Ford Mustang GT Premium Convertible 2022 - Fair Deal (Convertible!)
    {
      sellerId: dealer1.id,
      make: 'Ford',
      model: 'Mustang',
      year: 2022,
      trim: 'GT Premium Convertible',
      bodyType: 'Convertible',
      mileage: 19800,
      price: 38900,
      vin: '1FA6P8CF4N5192038',
      description: 'Open-air V8 muscle roar. 450 HP 5.0L Coyote V8, active valve performance exhaust, MagneRide damping system, digital gauge cluster, and heated/cooled leather seats.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7831,
      lng: -96.8067,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Shadow Black',
      interiorColor: 'Ebony Leather',
      condition: 'Certified Pre-Owned',
      engine: '5.0L Ti-VCT V8 450hp',
      features: JSON.stringify(['Active Valve Exhaust', 'MagneRide Damping', 'Digital Cluster', 'Heated/Cooled Seats', 'B&O Audio']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 44. Jeep Wrangler 4xe 2023 - Great Deal (Plug-in Hybrid & 4WD!)
    {
      sellerId: dealer3.id,
      make: 'Jeep',
      model: 'Wrangler',
      year: 2023,
      trim: 'Rubicon 4xe PHEV',
      bodyType: 'SUV',
      mileage: 14200,
      price: 46900,
      vin: '1C4JJXR68PW109283',
      description: 'Trail-rated plug-in hybrid with 375 HP and 470 lb-ft torque. Tru-Lok electronic locking differentials, electronic sway bar disconnect, Alpine premium sound, and Sky One-Touch power roof.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.8781,
      lng: -87.6298,
      fuelType: 'Plug-in Hybrid',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Hydro Blue Pearlcoat',
      interiorColor: 'Black Leather with Blue Accent Stitching',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo PHEV 375hp',
      features: JSON.stringify(['Plug-in Hybrid 375hp', 'Tru-Lok Front/Rear Lockers', 'Sky One-Touch Roof', 'Alpine Sound', 'Rock-Trac 4x4']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 45. Ford F-250 Super Duty 2022 - Fair Deal (Diesel Truck!)
    {
      sellerId: dealer1.id,
      make: 'Ford',
      model: 'F-250',
      year: 2022,
      trim: 'Super Duty Lariat 4WD Crew Cab',
      bodyType: 'Truck',
      mileage: 34000,
      price: 62500,
      vin: '1FT8W2BT5NEC19203',
      description: 'Heavy duty workhorse powered by the 6.7L Power Stroke V8 Turbo Diesel delivering 1,050 lb-ft torque. FX4 Off-Road package, 12-inch SYNC 4 touchscreen, B&O audio, and 20,000 lb towing capability.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7767,
      lng: -96.797,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Oxford White',
      interiorColor: 'Black Onyx Leather',
      condition: 'Used',
      engine: '6.7L Power Stroke Turbo Diesel 475hp 1050lb-ft',
      features: JSON.stringify(['Power Stroke Turbo Diesel', 'FX4 Off-Road', '12-inch SYNC 4', 'Pro Trailer Backup Assist', 'Leather Seats']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 7,
      images: [
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 46. Chevrolet Silverado 1500 Duramax 2021 - Great Deal (Diesel Truck!)
    {
      sellerId: dealer3.id,
      make: 'Chevrolet',
      model: 'Silverado',
      year: 2021,
      trim: '1500 RST 3.0L Duramax 4WD',
      bodyType: 'Truck',
      mileage: 28500,
      price: 38900,
      vin: '1GCPYDEF8MZ291048',
      description: 'Exceptional 33 MPG highway fuel efficiency with the 3.0L inline-6 Duramax Turbo-Diesel. Z71 Off-Road package, dual-zone climate, Bose audio, spray-on bedliner, and multi-flex tailgate.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.8781,
      lng: -87.6298,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Satin Steel Metallic',
      interiorColor: 'Jet Black Cloth',
      condition: 'Used',
      engine: '3.0L Duramax Turbo-Diesel 277hp 460lb-ft',
      features: JSON.stringify(['Duramax 33 MPG Highway', 'Z71 Off-Road', 'Multi-Flex Tailgate', 'Apple CarPlay', 'Heated Steering Wheel']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 47. Subaru WRX 2022 - Great Deal (Manual AWD Sedan!)
    {
      sellerId: dealer2.id,
      make: 'Subaru',
      model: 'WRX',
      year: 2022,
      trim: 'Premium 6-Speed Manual',
      bodyType: 'Sedan',
      mileage: 16500,
      price: 27900,
      vin: 'JF1VBGZ60N8819204',
      description: 'Rally-bred performance sedan with Symmetrical All-Wheel Drive, 2.4-liter turbocharged BOXER engine, short-throw 6-speed manual, 11.6-inch Starlink touchscreen, and 18-inch dark gray alloy wheels.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Gasoline',
      transmission: 'Manual',
      drivetrain: 'AWD',
      exteriorColor: 'WR Blue Pearl',
      interiorColor: 'Black Cloth with Red Contrast Stitching',
      condition: 'Used',
      engine: '2.4L Turbocharged Boxer 271hp',
      features: JSON.stringify(['6-Speed Manual', 'Symmetrical AWD', '11.6-inch Touchscreen', 'Short Throw Shifter', 'Keyless Access']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 48. Hyundai Ioniq 5 2023 - Great Deal (Electric Hatchback!)
    {
      sellerId: dealer2.id,
      make: 'Hyundai',
      model: 'Ioniq 5',
      year: 2023,
      trim: 'SEL AWD',
      bodyType: 'Hatchback',
      mileage: 13500,
      price: 31800,
      vin: 'KM8KRDAE9PU192038',
      description: 'Futuristic design with ultra-fast 800V charging (10% to 80% in 18 minutes). Dual motor AWD produces 320 HP, Highway Driving Assist II, ambient mood lighting, and flat cabin floor spaciousness.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94103',
      lat: 37.779,
      lng: -122.415,
      fuelType: 'Electric',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Cyber Gray',
      interiorColor: 'Dark Green / Gray H-Tex',
      condition: 'Used',
      engine: 'Dual-Motor Electric 320hp',
      features: JSON.stringify(['800V Ultra-Fast Charging', 'Dual Motor AWD', 'Highway Driving Assist II', 'Wireless Phone Charger', 'Smart Power Liftgate']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=1200&auto=format&fit=crop&q=80',
      ],
    },

    // 49. Mercedes-Benz GLE 350 2022 - Fair Deal
    {
      sellerId: dealer1.id,
      make: 'Mercedes-Benz',
      model: 'GLE 350',
      year: 2022,
      trim: '4MATIC SUV',
      bodyType: 'SUV',
      mileage: 26000,
      price: 48900,
      vin: '4JGFF4KB8NA192038',
      description: 'Sophisticated luxury with 4MATIC All-Wheel Drive, dual 12.3-inch widescreen displays, Burmester surround sound, ambient 64-color lighting, panoramic sunroof, and MB-Tex upholstery.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7767,
      lng: -96.797,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Polar White',
      interiorColor: 'Macchiato Beige MB-Tex',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo 255hp',
      features: JSON.stringify(['4MATIC AWD', 'Burmester Surround', 'Dual 12.3-inch Screens', 'Panoramic Roof', 'Parktronic']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1563720223185-11003d516935?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 50. Audi Q5 2022 - Great Deal
    {
      sellerId: dealer2.id,
      make: 'Audi',
      model: 'Q5',
      year: 2022,
      trim: '45 S line Premium Plus',
      bodyType: 'SUV',
      mileage: 21000,
      price: 34500,
      vin: 'WA1BNAFY7N2019483',
      description: 'Pristine Audi Q5 45 TFSI S line with quattro AWD. Virtual Cockpit Plus, Bang & Olufsen 3D sound, panoramic sunroof, top-view 360 camera, and Audi pre sense safety tech.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Glacier White Metallic',
      interiorColor: 'Black Leather with Rock Gray Stitching',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo 261hp',
      features: JSON.stringify(['quattro AWD', 'Virtual Cockpit', 'Bang & Olufsen 3D', '360 Camera', 'S Line Exterior']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 51. Kia EV6 2023 - Great Deal
    {
      sellerId: dealer3.id,
      make: 'Kia',
      model: 'EV6',
      year: 2023,
      trim: 'Wind AWD Electric',
      bodyType: 'SUV',
      mileage: 15200,
      price: 33900,
      vin: 'KNDCE3LG6P5102948',
      description: 'Electrifying performance with 320 HP dual-motor AWD. 800V fast-charging architecture, Meridian 14-speaker audio, dual 12.3-inch curved panoramic displays, and smart power tailgate.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.8781,
      lng: -87.6298,
      fuelType: 'Electric',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Steel Matte Gray',
      interiorColor: 'Black SynTex Suede',
      condition: 'Used',
      engine: 'Dual-Motor Electric 320hp',
      features: JSON.stringify(['800V Ultra-Fast Charging', 'Dual Motor AWD', 'Meridian Sound', 'Dual 12.3 Curved Screens', 'Heat Pump']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=1200&auto=format&fit=crop&q=80',
      ],
    },
];

  for (const car of listingsData) {
    const { images, ...carData } = car;
    const listing = await prisma.listing.create({
      data: {
        ...carData,
        location: `${carData.city}, ${carData.state}`,
      },
    });

    for (let i = 0; i < images.length; i++) {
      await prisma.listingImage.create({
        data: {
          listingId: listing.id,
          url: images[i],
          order: i,
          isPrimary: i === 0,
        },
      });
    }
  }

  // Create initial demo favorites and saved searches for demo buyer
  const sampleCamry = await prisma.listing.findFirst({ where: { make: 'Toyota', model: 'Camry' } });
  const sampleCorvette = await prisma.listing.findFirst({ where: { make: 'Chevrolet', model: 'Corvette' } });

  if (sampleCamry) {
    await prisma.favorite.create({
      data: {
        userId: demoBuyer.id,
        listingId: sampleCamry.id,
      },
    });
  }

  if (sampleCorvette) {
    await prisma.favorite.create({
      data: {
        userId: demoBuyer.id,
        listingId: sampleCorvette.id,
      },
    });
  }

  await prisma.savedSearch.create({
    data: {
      userId: demoBuyer.id,
      name: 'Great Deals on Toyota Sedans',
      filtersJson: JSON.stringify({ make: 'Toyota', bodyType: 'Sedan', dealRating: 'great' }),
    },
  });

  await prisma.savedSearch.create({
    data: {
      userId: demoBuyer.id,
      name: 'Trucks under $45,000',
      filtersJson: JSON.stringify({ bodyType: 'Truck', maxPrice: '45000' }),
    },
  });

  // Sample buyer message to dealer 1
  if (sampleCamry) {
    await prisma.message.create({
      data: {
        fromUserId: demoBuyer.id,
        toUserId: dealer1.id,
        listingId: sampleCamry.id,
        body: 'Hi, is this 2022 Toyota Camry SE still available for a test drive this Saturday?',
      },
    });

    await prisma.inquiryLead.create({
      data: {
        listingId: sampleCamry.id,
        buyerName: demoBuyer.name,
        buyerEmail: demoBuyer.email,
        buyerPhone: demoBuyer.phone,
        message: 'Interested in financing options and trade-in value for my current vehicle.',
        status: 'NEW',
      },
    });
  }

  console.log(`Seeding complete! Successfully created 32 listings and initial data.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
