const fs = require('fs');

let seedContent = fs.readFileSync('d:/antigravity/TrueGear/prisma/seed.ts', 'utf8');

// 1. Fix broken URLs
seedContent = seedContent.replace(
  /'https:\/\/images\.unsplash\.com\/photo-1541348263662-e0c8666574ec\?w=1200&auto=format&fit=crop&q=80'/g,
  (match, offset) => {
    // In Audi A4 (first occurrence around line 990)
    return `'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=1200&auto=format&fit=crop&q=80'`;
  }
);

// 2. Prepare new listings data
const newCarsCode = `
    // 33. Lexus RX 350 2022 - Great Deal
    {
      sellerId: dealer1.id,
      make: 'Lexus',
      model: 'RX 350',
      year: 2022,
      trim: 'F SPORT AWD',
      bodyType: 'SUV',
      mileage: 22000,
      price: 41500,
      vin: '2T2BZMCA4NC109283',
      description: 'Stunning Lexus RX 350 F SPORT with Mark Levinson 15-speaker audio, triple-beam LED headlights, panorama glass roof, heated/ventilated seats, and comprehensive LSS+ 2.0 safety suite.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7767,
      lng: -96.797,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Ultra White',
      interiorColor: 'Circuit Red Leather',
      condition: 'Certified Pre-Owned',
      engine: '3.5L V6 295hp',
      features: JSON.stringify(['Mark Levinson Audio', 'F SPORT Tuned Suspension', 'Panoramic Roof', 'Heated & Ventilated Seats', 'Navigation']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 6,
      images: [
        'https://images.unsplash.com/photo-1508974239320-0a029497e820?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 34. Lexus ES 300h 2023 - Fair Deal
    {
      sellerId: dealer2.id,
      make: 'Lexus',
      model: 'ES 300h',
      year: 2023,
      trim: 'Ultra Luxury Hybrid',
      bodyType: 'Sedan',
      mileage: 16800,
      price: 43900,
      vin: '58ABZ1B17PU089211',
      description: 'Ultra Luxury ES 300h achieving 44 MPG combined. Semi-aniline leather, genuine wood trim, heads-up display, hands-free power trunk, and whisper-quiet hybrid serenity.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Hybrid',
      transmission: 'Automatic',
      drivetrain: 'FWD',
      exteriorColor: 'Eminent White Pearl',
      interiorColor: 'Acorn Semi-Aniline Leather',
      condition: 'Used',
      engine: '2.5L 4-Cylinder Hybrid 215hp',
      features: JSON.stringify(['Semi-Aniline Leather', '44 MPG Hybrid', 'Heads Up Display', 'Panoramic Glass Roof', 'Blind Spot Monitor']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 35. Nissan Rogue 2022 - Great Deal
    {
      sellerId: dealer3.id,
      make: 'Nissan',
      model: 'Rogue',
      year: 2022,
      trim: 'SV AWD',
      bodyType: 'SUV',
      mileage: 25400,
      price: 21900,
      vin: 'JN8BT3BB6NW284910',
      description: 'Practical and modern Rogue SV with 1.5L VC-Turbo engine, Intelligent All-Wheel Drive, ProPILOT Assist, dual-zone automatic climate control, and remote engine start.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.8781,
      lng: -87.6298,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Gun Metallic',
      interiorColor: 'Charcoal Cloth',
      condition: 'Used',
      engine: '1.5L VC-Turbo 201hp',
      features: JSON.stringify(['ProPILOT Assist', 'Intelligent AWD', 'Apple CarPlay', 'Remote Start', 'Blind Spot Warning']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1592853625597-7d17be820d0c?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 36. Nissan GT-R 2021 - High Price
    {
      sellerId: dealer1.id,
      make: 'Nissan',
      model: 'GT-R',
      year: 2021,
      trim: 'Premium AWD',
      bodyType: 'Coupe',
      mileage: 12000,
      price: 119500,
      vin: 'JN1AR5EF7MM710294',
      description: 'The legendary Godzilla. Handcrafted 3.8-liter twin-turbo V6 with 565 HP, ATTESA E-TS All-Wheel Drive, Bilstein DampTronic suspension, Brembo braking system, and Bose sound.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7845,
      lng: -96.8012,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Super Silver QuadCoat',
      interiorColor: 'Amber Hand-Stitched Leather',
      condition: 'Used',
      engine: '3.8L Twin-Turbo V6 565hp',
      features: JSON.stringify(['ATTESA AWD', 'Brembo Brakes', 'Bilstein DampTronic', 'Titanium Exhaust', 'Recaro Seats']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 37. Volkswagen Golf GTI 2023 - Great Deal (Hatchback & Manual!)
    {
      sellerId: dealer2.id,
      make: 'Volkswagen',
      model: 'Golf GTI',
      year: 2023,
      trim: 'SE 6-Speed Manual',
      bodyType: 'Hatchback',
      mileage: 14000,
      price: 28900,
      vin: '3VW547AU8PM092831',
      description: 'Purist delight Mark 8 Golf GTI equipped with a silky 6-speed manual transmission, VAQ limited-slip differential lock, Harman Kardon audio, sunroof, and plaid sport seats.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94103',
      lat: 37.779,
      lng: -122.415,
      fuelType: 'Gasoline',
      transmission: 'Manual',
      drivetrain: 'FWD',
      exteriorColor: 'Kings Red Metallic',
      interiorColor: 'Titan Black Scalepaper Plaid',
      condition: 'Used',
      engine: '2.0L Turbo 241hp',
      features: JSON.stringify(['6-Speed Manual', 'Limited Slip Diff', 'Harman Kardon Audio', 'Plaid Sport Seats', 'Digital Cockpit Pro']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 38. Volkswagen Tiguan 2022 - Fair Deal
    {
      sellerId: dealer3.id,
      make: 'Volkswagen',
      model: 'Tiguan',
      year: 2022,
      trim: 'SEL R-Line 4MOTION',
      bodyType: 'SUV',
      mileage: 24000,
      price: 27500,
      vin: '3VV4B7AX7NM192044',
      description: 'Sporty Tiguan SEL R-Line with 4MOTION All-Wheel Drive, panoramic sunroof, 20-inch alloy wheels, Fender premium audio, ventilated leather seats, and IQ.DRIVE safety suite.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.882,
      lng: -87.625,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Deep Black Pearl',
      interiorColor: 'Storm Gray Leather',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo 184hp',
      features: JSON.stringify(['4MOTION AWD', 'Panoramic Sunroof', 'Fender Audio', 'Ventilated Seats', 'R-Line Exterior']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 39. Volvo V60 Cross Country 2022 - Great Deal (Wagon!)
    {
      sellerId: dealer2.id,
      make: 'Volvo',
      model: 'V60',
      year: 2022,
      trim: 'Cross Country B5 AWD',
      bodyType: 'Wagon',
      mileage: 21500,
      price: 36800,
      vin: 'YV4102SK7N1294810',
      description: 'The definitive luxury all-road wagon. 8.3-inch ground clearance, standard All-Wheel Drive, Google built-in infotainment, Bowers & Wilkins sound option, and ultra-comfortable orthopedic seats.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Pine Grey Metallic',
      interiorColor: 'Amber Nappa Leather',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo Mild Hybrid 247hp',
      features: JSON.stringify(['Cross Country Raised Suspension', 'AWD', 'Pilot Assist', 'Panoramic Sunroof', 'Bowers & Wilkins Audio']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 40. Volvo XC90 Recharge 2023 - Fair Deal (PHEV!)
    {
      sellerId: dealer1.id,
      make: 'Volvo',
      model: 'XC90',
      year: 2023,
      trim: 'Recharge Plus AWD 7-Passenger',
      bodyType: 'SUV',
      mileage: 18500,
      price: 54900,
      vin: 'YV4BR0UL4P1394012',
      description: '7-passenger Plug-in Hybrid luxury SUV delivering 455 horsepower and 35 miles of pure electric driving. Air suspension, 360 camera, adaptive cruise with lane centering, and panoramic roof.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7767,
      lng: -96.797,
      fuelType: 'Plug-in Hybrid',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Crystal White',
      interiorColor: 'Charcoal Leather',
      condition: 'Used',
      engine: '2.0L Turbo PHEV 455hp',
      features: JSON.stringify(['Plug-in Hybrid 455hp', '3-Row 7-Seater', 'Air Suspension', '360 Surround Camera', 'Pilot Assist']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1617469767053-d3b523a0b982?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 41. Mazda MX-5 Miata 2022 - Great Deal (Convertible & Manual!)
    {
      sellerId: dealer1.id,
      make: 'Mazda',
      model: 'MX-5 Miata',
      year: 2022,
      trim: 'Club 6-Speed Manual',
      bodyType: 'Convertible',
      mileage: 11200,
      price: 26800,
      vin: 'JM1NDAM76N0491028',
      description: 'The world benchmark sports roadster. Bilstein sport dampers, limited-slip differential, Brembo/BBS package, crisp 6-speed manual, soft top drop in seconds, and pure 50:50 driving balance.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7845,
      lng: -96.8012,
      fuelType: 'Gasoline',
      transmission: 'Manual',
      drivetrain: 'RWD',
      exteriorColor: 'Jet Black Mica',
      interiorColor: 'Black Cloth with Red Stitching',
      condition: 'Used',
      engine: '2.0L SKYACTIV-G 181hp',
      features: JSON.stringify(['Manual 6-Speed', 'Brembo Brakes', 'BBS Wheels', 'Bilstein Dampers', 'LSD Differential']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 42. Porsche 911 Carrera S Cabriolet 2021 - High Price (Convertible!)
    {
      sellerId: dealer2.id,
      make: 'Porsche',
      model: '911',
      year: 2021,
      trim: 'Carrera S Cabriolet',
      bodyType: 'Convertible',
      mileage: 15400,
      price: 134000,
      vin: 'WP0CB2A96MS291048',
      description: 'Exquisite 992-generation 911 Carrera S Cabriolet in Guards Red. 443 hp twin-turbo flat-six, 8-speed PDK, Sport Chrono package, sport exhaust system, 18-way adaptive sport seats, and front axle lift.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Guards Red',
      interiorColor: 'Black Full Leather',
      condition: 'Used',
      engine: '3.0L Twin-Turbo Flat-6 443hp',
      features: JSON.stringify(['Sport Chrono Package', 'Sport Exhaust', 'Front Axle Lift', 'BOSE Surround Audio', '18-Way Sport Seats']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 43. Ford Mustang GT Premium Convertible 2022 - Fair Deal (Convertible!)
    {
      sellerId: dealer1.id,
      make: 'Ford',
      model: 'Mustang',
      year: 2022,
      trim: 'GT Premium Convertible',
      bodyType: 'Convertible',
      mileage: 19800,
      price: 38900,
      vin: '1FA6P8CF4N5192038',
      description: 'Open-air V8 muscle roar. 450 HP 5.0L Coyote V8, active valve performance exhaust, MagneRide damping system, digital gauge cluster, and heated/cooled leather seats.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7831,
      lng: -96.8067,
      fuelType: 'Gasoline',
      transmission: 'Automatic',
      drivetrain: 'RWD',
      exteriorColor: 'Shadow Black',
      interiorColor: 'Ebony Leather',
      condition: 'Certified Pre-Owned',
      engine: '5.0L Ti-VCT V8 450hp',
      features: JSON.stringify(['Active Valve Exhaust', 'MagneRide Damping', 'Digital Cluster', 'Heated/Cooled Seats', 'B&O Audio']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1553440569-bcc63803a83d?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 44. Jeep Wrangler 4xe 2023 - Great Deal (Plug-in Hybrid & 4WD!)
    {
      sellerId: dealer3.id,
      make: 'Jeep',
      model: 'Wrangler',
      year: 2023,
      trim: 'Rubicon 4xe PHEV',
      bodyType: 'SUV',
      mileage: 14200,
      price: 46900,
      vin: '1C4JJXR68PW109283',
      description: 'Trail-rated plug-in hybrid with 375 HP and 470 lb-ft torque. Tru-Lok electronic locking differentials, electronic sway bar disconnect, Alpine premium sound, and Sky One-Touch power roof.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.8781,
      lng: -87.6298,
      fuelType: 'Plug-in Hybrid',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Hydro Blue Pearlcoat',
      interiorColor: 'Black Leather with Blue Accent Stitching',
      condition: 'Certified Pre-Owned',
      engine: '2.0L Turbo PHEV 375hp',
      features: JSON.stringify(['Plug-in Hybrid 375hp', 'Tru-Lok Front/Rear Lockers', 'Sky One-Touch Roof', 'Alpine Sound', 'Rock-Trac 4x4']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 45. Ford F-250 Super Duty 2022 - Fair Deal (Diesel Truck!)
    {
      sellerId: dealer1.id,
      make: 'Ford',
      model: 'F-250',
      year: 2022,
      trim: 'Super Duty Lariat 4WD Crew Cab',
      bodyType: 'Truck',
      mileage: 34000,
      price: 62500,
      vin: '1FT8W2BT5NEC19203',
      description: 'Heavy duty workhorse powered by the 6.7L Power Stroke V8 Turbo Diesel delivering 1,050 lb-ft torque. FX4 Off-Road package, 12-inch SYNC 4 touchscreen, B&O audio, and 20,000 lb towing capability.',
      city: 'Dallas',
      state: 'TX',
      zip: '75201',
      lat: 32.7767,
      lng: -96.797,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Oxford White',
      interiorColor: 'Black Onyx Leather',
      condition: 'Used',
      engine: '6.7L Power Stroke Turbo Diesel 475hp 1050lb-ft',
      features: JSON.stringify(['Power Stroke Turbo Diesel', 'FX4 Off-Road', '12-inch SYNC 4', 'Pro Trailer Backup Assist', 'Leather Seats']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 7,
      images: [
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 46. Chevrolet Silverado 1500 Duramax 2021 - Great Deal (Diesel Truck!)
    {
      sellerId: dealer3.id,
      make: 'Chevrolet',
      model: 'Silverado',
      year: 2021,
      trim: '1500 RST 3.0L Duramax 4WD',
      bodyType: 'Truck',
      mileage: 28500,
      price: 38900,
      vin: '1GCPYDEF8MZ291048',
      description: 'Exceptional 33 MPG highway fuel efficiency with the 3.0L inline-6 Duramax Turbo-Diesel. Z71 Off-Road package, dual-zone climate, Bose audio, spray-on bedliner, and multi-flex tailgate.',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
      lat: 41.8781,
      lng: -87.6298,
      fuelType: 'Diesel',
      transmission: 'Automatic',
      drivetrain: '4WD',
      exteriorColor: 'Satin Steel Metallic',
      interiorColor: 'Jet Black Cloth',
      condition: 'Used',
      engine: '3.0L Duramax Turbo-Diesel 277hp 460lb-ft',
      features: JSON.stringify(['Duramax 33 MPG Highway', 'Z71 Off-Road', 'Multi-Flex Tailgate', 'Apple CarPlay', 'Heated Steering Wheel']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 5,
      images: [
        'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 47. Subaru WRX 2022 - Great Deal (Manual AWD Sedan!)
    {
      sellerId: dealer2.id,
      make: 'Subaru',
      model: 'WRX',
      year: 2022,
      trim: 'Premium 6-Speed Manual',
      bodyType: 'Sedan',
      mileage: 16500,
      price: 27900,
      vin: 'JF1VBGZ60N8819204',
      description: 'Rally-bred performance sedan with Symmetrical All-Wheel Drive, 2.4-liter turbocharged BOXER engine, short-throw 6-speed manual, 11.6-inch Starlink touchscreen, and 18-inch dark gray alloy wheels.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94102',
      lat: 37.7749,
      lng: -122.4194,
      fuelType: 'Gasoline',
      transmission: 'Manual',
      drivetrain: 'AWD',
      exteriorColor: 'WR Blue Pearl',
      interiorColor: 'Black Cloth with Red Contrast Stitching',
      condition: 'Used',
      engine: '2.4L Turbocharged Boxer 271hp',
      features: JSON.stringify(['6-Speed Manual', 'Symmetrical AWD', '11.6-inch Touchscreen', 'Short Throw Shifter', 'Keyless Access']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 4,
      images: [
        'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?w=1200&auto=format&fit=crop&q=80',
      ],
    },
    // 48. Hyundai Ioniq 5 2023 - Great Deal (Electric Hatchback!)
    {
      sellerId: dealer2.id,
      make: 'Hyundai',
      model: 'Ioniq 5',
      year: 2023,
      trim: 'SEL AWD',
      bodyType: 'Hatchback',
      mileage: 13500,
      price: 31800,
      vin: 'KM8KRDAE9PU192038',
      description: 'Futuristic design with ultra-fast 800V charging (10% to 80% in 18 minutes). Dual motor AWD produces 320 HP, Highway Driving Assist II, ambient mood lighting, and flat cabin floor spaciousness.',
      city: 'San Francisco',
      state: 'CA',
      zip: '94103',
      lat: 37.779,
      lng: -122.415,
      fuelType: 'Electric',
      transmission: 'Automatic',
      drivetrain: 'AWD',
      exteriorColor: 'Cyber Gray',
      interiorColor: 'Dark Green / Gray H-Tex',
      condition: 'Used',
      engine: 'Dual-Motor Electric 320hp',
      features: JSON.stringify(['800V Ultra-Fast Charging', 'Dual Motor AWD', 'Highway Driving Assist II', 'Wireless Phone Charger', 'Smart Power Liftgate']),
      accidents: 0,
      previousOwners: 1,
      serviceHistory: 3,
      images: [
        'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=1200&auto=format&fit=crop&q=80',
      ],
    },
`;

// Insert newCarsCode right before `];\n\n  for (const car of listingsData)`
const targetIdx = seedContent.indexOf('];\n\n  for (const car of listingsData)');
if (targetIdx === -1) {
  console.error('Could not locate end of listingsData');
  process.exit(1);
}

const updatedSeed = seedContent.slice(0, targetIdx) + newCarsCode + seedContent.slice(targetIdx);
fs.writeFileSync('d:/antigravity/TrueGear/prisma/seed.ts', updatedSeed, 'utf8');
console.log('Successfully updated prisma/seed.ts with 48 listings!');
